import type { Locale } from "@/lib/translations"

const copy = {
  it: { unavailable: "La conversazione AI non è disponibile al momento. Posso ancora aiutarti con le informazioni essenziali del negozio.", limited: "Assistenza essenziale · AI non disponibile", interrupted: "La risposta si è interrotta. Prova a chiedermelo di nuovo.", stop: "Interrompi risposta", read: "Leggi risposta", thinking: "Sto pensando…", listening: "Ti ascolto", speaking: "Ti rispondo", ready: "Parliamone", clear: "Nuova conversazione", tooMany: "Hai inviato molte richieste. Aspetta un minuto e riprova." },
  en: { unavailable: "AI conversation is currently unavailable. I can still help with essential store information.", limited: "Basic assistance · AI unavailable", interrupted: "The reply was interrupted. Please ask me again.", stop: "Stop response", read: "Read response aloud", thinking: "Thinking…", listening: "Listening", speaking: "Replying", ready: "Let's talk", clear: "New conversation", tooMany: "You've sent many requests. Please wait a minute and try again." },
  es: { unavailable: "La conversación con IA no está disponible ahora. Aún puedo ayudarte con información básica de la tienda.", limited: "Asistencia básica · IA no disponible", interrupted: "La respuesta se ha interrumpido. Pregúntame de nuevo.", stop: "Detener respuesta", read: "Leer respuesta", thinking: "Pensando…", listening: "Te escucho", speaking: "Respondiendo", ready: "Hablemos", clear: "Nueva conversación", tooMany: "Has enviado muchas solicitudes. Espera un minuto e inténtalo de nuevo." },
  de: { unavailable: "Die KI-Unterhaltung ist derzeit nicht verfügbar. Ich kann weiterhin grundlegende Shop-Informationen anbieten.", limited: "Basishilfe · KI nicht verfügbar", interrupted: "Die Antwort wurde unterbrochen. Bitte frag mich erneut.", stop: "Antwort stoppen", read: "Antwort vorlesen", thinking: "Ich denke nach…", listening: "Ich höre zu", speaking: "Ich antworte", ready: "Lass uns reden", clear: "Neues Gespräch", tooMany: "Du hast viele Anfragen gesendet. Bitte warte eine Minute und versuche es erneut." },
  fr: { unavailable: "La conversation IA est indisponible pour le moment. Je peux encore vous aider avec les informations essentielles de la boutique.", limited: "Aide essentielle · IA indisponible", interrupted: "La réponse a été interrompue. Posez-moi à nouveau la question.", stop: "Arrêter la réponse", read: "Lire la réponse", thinking: "Je réfléchis…", listening: "Je vous écoute", speaking: "Je réponds", ready: "Parlons-en", clear: "Nouvelle conversation", tooMany: "Vous avez envoyé beaucoup de demandes. Attendez une minute et réessayez." },
}

export function miraCopy(locale: Locale) { return copy[locale] }
